"""init full schema

Revision ID: 8406ed51d10f
Revises: 
Create Date: 2026-08-03 11:07:46.765693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8406ed51d10f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fare_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('baggage_allowance_kg', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pnr', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_email', sa.String(), nullable=True),
    sa.Column('guest_phone', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=True)
    op.create_table('featured_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_passengers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('passenger_type', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('frequent_flyer_number', sa.String(), nullable=True),
    sa.Column('special_assistance', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('departure_time_local', sa.Time(), nullable=False),
    sa.Column('arrival_time_local', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=True)
    op.create_table('flight_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['flight_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('flight_instance_id', sa.UUID(), nullable=False),
    sa.Column('fare_class_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['fare_class_id'], ['fare_classes.id'], ),
    sa.ForeignKeyConstraint(['flight_instance_id'], ['flight_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_fares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_instance_id', sa.UUID(), nullable=False),
    sa.Column('fare_class_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fare_class_id'], ['fare_classes.id'], ),
    sa.ForeignKeyConstraint(['flight_instance_id'], ['flight_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_instance_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('is_window', sa.Boolean(), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), nullable=False),
    sa.Column('is_extra_legroom', sa.Boolean(), nullable=False),
    sa.Column('is_emergency_exit', sa.Boolean(), nullable=False),
    sa.Column('extra_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flight_instance_id'], ['flight_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_seat_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_passenger_id', sa.UUID(), nullable=False),
    sa.Column('booking_segment_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_passenger_id'], ['booking_passengers.id'], ),
    sa.ForeignKeyConstraint(['booking_segment_id'], ['booking_segments.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_seat_assignments')
    op.drop_table('seats')
    op.drop_table('flight_fares')
    op.drop_table('booking_segments')
    op.drop_table('flight_instances')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('flight_schedules')
    op.drop_table('booking_passengers')
    op.drop_table('routes')
    op.drop_table('featured_destinations')
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_table('fare_classes')
    op.drop_table('deals')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_table('airlines')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###